import type { AgentDefinition } from "@jiuwen-sci/core";

export const literatureAgents: AgentDefinition[] = [
  { id: "literature-orchestrator", name: "Literature Orchestrator", description: "Coordinates PRISMA-style literature review tasks.", mode: "subagent", prompt: "Coordinate a PRISMA-style literature review using artifacts for all intermediate outputs.", permissions: [], allowedTools: ["task", "artifact_read", "artifact_write", "finalize"], maxTurns: 8 },
  { id: "literature-query-agent", name: "Literature Query Agent", description: "Builds search plans and inclusion/exclusion criteria.", mode: "subagent", prompt: "Define research question, concepts, selected queries, alternative queries, and IC/EC criteria before screening.", permissions: [], allowedTools: ["artifact_write", "finalize"], maxTurns: 6 },
  { id: "literature-search-agent", name: "Literature Search Agent", description: "Runs multi-database literature searches and citation chaining.", mode: "subagent", prompt: "Search multiple scientific databases, record source errors, and avoid fabricating records.", permissions: [], allowedTools: ["science_list_dbs", "science_search", "paper_fetch", "citation_chain", "paper_deduplicate", "artifact_write", "finalize"], maxTurns: 6 },
  { id: "literature-screening-agent", name: "Literature Screening Agent", description: "Screens candidate papers using explicit IC/EC rules.", mode: "subagent", prompt: "Apply explicit inclusion/exclusion criteria and record a reason for every decision.", permissions: [], allowedTools: ["artifact_read", "artifact_write", "finalize"], maxTurns: 6 },
  { id: "literature-eligibility-agent", name: "Literature Eligibility Agent", description: "Assesses eligible papers using available abstract/full-text metadata.", mode: "subagent", prompt: "Assess abstract/full-text eligibility and record exclusion reasons.", permissions: [], allowedTools: ["artifact_read", "artifact_write", "finalize"], maxTurns: 6 },
  { id: "literature-quality-agent", name: "Literature Quality Agent", description: "Assigns evidence quality tiers.", mode: "subagent", prompt: "Assign quality tiers using venue, peer review, citation metadata, recency, and available empirical detail.", permissions: [], allowedTools: ["artifact_read", "artifact_write", "finalize"], maxTurns: 6 },
  { id: "literature-synthesis-agent", name: "Literature Synthesis Agent", description: "Synthesizes evidence and contradictions thematically.", mode: "subagent", prompt: "Synthesize evidence thematically. Every claim must cite evidence rows; explicitly flag contradictions.", permissions: [], allowedTools: ["artifact_read", "evidence_table_write", "artifact_write", "finalize"], maxTurns: 6 },
  { id: "literature-citation-agent", name: "Literature Citation Agent", description: "Verifies citations and writes BibTeX.", mode: "subagent", prompt: "Verify citations and generate BibTeX. Mark unverified records explicitly.", permissions: [], allowedTools: ["citation_verify", "bibtex_write", "artifact_read", "artifact_write", "finalize"], maxTurns: 6 },
  { id: "literature-reviewer-agent", name: "Literature Reviewer", description: "Checks citation, evidence, claim, and PRISMA integrity.", mode: "subagent", prompt: "Blindly audit citation support, untraceable claims, screening completeness, and PRISMA count consistency. Record findings if needed.", permissions: [], allowedTools: ["artifact_read", "citation_check", "review_finding_write", "finalize"], maxTurns: 6 }
];
